import axios from "axios";

/*we make can api call to store the reponseToken we have created for the requestToken generated by the verifier 
//when applying for an e-government service. Also we send all the images uploaded by the user */
export async function storeResponseToken(cred, applicantType, images) {
  const response = axios({
    method: "post",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/ResponseToken",
    data: {
      responseToken: cred, //responseToken
      applicationType: applicantType, //here the type of e-government service is metioned can be eiter "renew work permit " or "work permit "
      images: images, //the images selected by the student example visa,passport ,bank statements
    },
  }).then((res) => {
    console.log(res);
  });
}

//api call to post the response token to firebase
export async function getAllResponseToken() {
  const response = await axios({
    method: "get",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/ResponseToken",
  })
    .then((res) => {
      return res;
    })
    .catch((err) => {
      console.log("Info", err);
    });

  const responseData = await response.data;

  return responseData;
}

//api call to delete resposne token
export async function deleteResponseToken(applicationType, responseToken) {
  const response = await axios({
    method: "delete",
    data: {
      applicationType: applicationType,
      responseToken: responseToken,
    },
    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/ResponseToken",
  }).catch((err) => {
    console.log("Info", err);
  });
}

//api call to upload application details to firebase
export async function postApplication(data) {
  const response = axios({
    method: "post",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/application",
    data: data,
  })
    .then((res) => {})
    .catch((err) => {
      console.log("Info", err);
    });
}

//get all the application sent by the stundent to the issuer
export async function getAllApplication() {
  const response = await axios({
    method: "get",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/applications",
  })
    .then((res) => {
      return res;
    })
    .catch((err) => {
      console.log("Info", err);
    });

  const responseData = await response.data;

  return responseData;
}

//api call to delete application form sent to the issuer after it has been signed
export async function deleteApplication(did, applicationType) {
  const response = await axios({
    method: "delete",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/application",
    data: {
      did: did,
      applicationType: applicationType,
    },
  })
    .then(() => {})
    .catch((err) => {
      console.log("Info", err);
    });
}

//api call to upload a vc to firebase
export async function postVC(data) {
  const response = axios({
    method: "post",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/proof",
    data: data,
  })
    .then((res) => {})
    .catch((err) => {
      console.log("Info", err);
    });
}
//we make an api to get te verifiable crdential from the firestore database
// after the issuer has uploaded the verifiable credential
export async function getVC() {
  const response = await axios({
    method: "get",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/proof",
  })
    .then((res) => {
      return res;
    })
    .catch((err) => {
      console.log("Info", err);
    });

  const responseData = await response.data;

  return responseData;
}

//api call to delte vc in the database after it has been store in the cloud wallet
export async function deleteVC(claimid) {
  const response = await axios({
    method: "delete",

    url: "https://europe-west1-socialape-201b4.cloudfunctions.net/api/proof",
    data: {
      claimerId: claimid,
    },
  }).catch((err) => {
    console.log("Info", err);
  });
}
